---
name: "release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: tag-new-version
        with:
          version-command: cat manifest.json | jq -r .version
      - uses: vimtor/action-zip@v1
        with:
          dest: codimd-zipper.zip
          files: dist/
        if: ${{ steps.tag-new-version.outputs.tag }}
      - uses: softprops/action-gh-release@v1
        with:
          files: codimd-zipper.zip
          generate_release_notes: true
          tag_name: ${{ steps.tag-new-version.outputs.tag }}
        if: ${{ steps.tag-new-version.outputs.tag }}
